POST http://localhost:3004
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  families (
    filter: {
      id: {
        _eq: 1
      }
    }
  ){
    id
    products (
      filter: {
        _and: [
          {
            id: {
              _in: [1,2,3,4]
            }
          }
          {
            _or: [
              {
                name: {
                  _like: "name1"
                }
              }
              {
                name: {
                  _like: "name2"
                }
              }
            ]
          }
        ]
      }
    ){
      id
      name
      FamilyId
      families {
        id
      }
    }
  }
}

###
POST http://localhost:3004
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  families (
    filter: {
      id: {
        _eq: "NonExistingId"
      }
    }
  ){
    id
    name
  }
}

###
POST http://localhost:3004
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  families (
    filter: {
      id: {
        _in: [1,2]
      }
    }
  ){
    id
    name
  }
}

###
POST http://localhost:3004
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation {
  addFamilies (
    data: {
      name: "TestFamily"
    }
  ){
    id
    name
  }
}


77554e6e-cc19-4d04-87af-1efb266e55cc
bea
2020-11-24T21:21:09.982Z
2020-11-24T21:21:09.982Z
 
77554e6e-cc19-4d04-87af-1efb266e55cd
test0
2020-11-24T21:21:09.982Z
2020-11-24T21:21:09.982Z
 
77554e6e-cc19-4d04-87af-1efb266e55ce
test1
2020-11-24T21:21:09.982Z
2020-11-24T21:21:09.982Z
 
894046ad-e391-4b05-b819-658c0ade4cc8
pedro
2020-11-24T21:21:09.982Z
2020-11-24T21:21:09.982Z
 
8b0c875e-2d84-4edf-ab7e-f0ba6edb4ca5
miriamm
2020-11-24T21:21:09.982Z
2020-11-24T21:21:09.982Z
 
a6775a43-d434-42f9-b693-16c2854218cb
jejay
2020-11-24T21:21:09.982Z
2020-11-24T21:21:09.982Z
 
dbf34edb-79cc-4a6d-b131-0f8d18cfe94b
leite
2020-11-24T21:21:09.982Z
2020-11-24T21:21:09.982Z
 
